-- Massa de dados adicional (generica) para enriquecer as estatisticas de demonstracao:
-- mais decadas, mais fabricantes e mais volume para os graficos/contagens.

INSERT INTO aeronave (nome, marca, ano, descricao, vendido, created, updated) VALUES
('ERJ-145',                'Embraer',          1996, 'Jato regional',                                true,  now() - interval '85 days', now() - interval '85 days'),
('Phenom 300',             'Embraer',          2009, 'Jato executivo leve',                           true,  now() - interval '80 days', now() - interval '80 days'),
('Praetor 600',            'Embraer',          2019, 'Jato executivo de medio porte',                 false, now() - interval '75 days', now() - interval '75 days'),
('707',                    'Boeing',           1958, 'Jato comercial pioneiro de longo alcance',       true,  now() - interval '70 days', now() - interval '70 days'),
('727',                    'Boeing',           1968, 'Jato comercial trijato',                         true,  now() - interval '65 days', now() - interval '65 days'),
('737-800',                'Boeing',           2003, 'Jato comercial de fuselagem estreita',           false, now() - interval '60 days', now() - interval '60 days'),
('787-9',                  'Boeing',           2014, 'Jato comercial de fuselagem larga',              false, now() - interval '55 days', now() - interval '55 days'),
('777-300ER',              'Boeing',           2006, 'Jato comercial de fuselagem larga de longo alcance', true, now() - interval '50 days', now() - interval '50 days'),
('A300',                   'Airbus',           1974, 'Primeiro bicorredor da Airbus',                  true,  now() - interval '45 days', now() - interval '45 days'),
('A310',                   'Airbus',           1983, 'Jato comercial de fuselagem larga',              true,  now() - interval '40 days', now() - interval '40 days'),
('A330-300',               'Airbus',           1994, 'Jato comercial de fuselagem larga',              false, now() - interval '38 days', now() - interval '38 days'),
('A380',                   'Airbus',           2007, 'Maior aviao comercial de passageiros do mundo',  false, now() - interval '35 days', now() - interval '35 days'),
('A220-300',                'Airbus',          2020, 'Jato comercial de corredor unico',               false, now() - interval '33 days', now() - interval '33 days'),
('Challenger 350',         'Bombardier',       2014, 'Jato executivo de medio porte',                  true,  now() - interval '30 days', now() - interval '30 days'),
('Global 6000',            'Bombardier',       2012, 'Jato executivo de longo alcance',                false, now() - interval '28 days', now() - interval '28 days'),
('Learjet 75',             'Bombardier',       2013, 'Jato executivo leve',                            true,  now() - interval '25 days', now() - interval '25 days'),
('Citation CJ4',           'Cessna',           2010, 'Jato executivo leve',                            false, now() - interval '22 days', now() - interval '22 days'),
('Citation Sovereign',     'Cessna',           2004, 'Jato executivo de medio porte',                  true,  now() - interval '20 days', now() - interval '20 days'),
('Skyhawk',                'Cessna',           1978, 'Aeronave monomotor de instrucao',                true,  now() - interval '18 days', now() - interval '18 days'),
('42-500',                 'ATR',              1995, 'Turboelice regional',                            false, now() - interval '16 days', now() - interval '16 days'),
('72-600',                 'ATR',              2013, 'Turboelice regional',                            false, now() - interval '14 days', now() - interval '14 days'),
('G550',                   'Gulfstream',       2003, 'Jato executivo de longo alcance',                true,  now() - interval '12 days', now() - interval '12 days'),
('G650',                   'Gulfstream',       2012, 'Jato executivo de longo alcance',                false, now() - interval '10 days', now() - interval '10 days'),
('Falcon 900',             'Dassault',         1986, 'Jato executivo trijato',                         true,  now() - interval '9 days',  now() - interval '9 days'),
('Falcon 7X',              'Dassault',         2007, 'Jato executivo trijato',                         false, now() - interval '8 days',  now() - interval '8 days'),
('C-130 Hercules',         'Lockheed Martin',  1965, 'Cargueiro militar turboelice',                   true,  now() - interval '6 days',  now() - interval '6 days'),
('L-1011 TriStar',         'Lockheed Martin',  1972, 'Jato comercial de fuselagem larga',              true,  now() - interval '5 days',  now() - interval '5 days'),
('PA-28 Cherokee',         'Piper',            1967, 'Aeronave monomotor de instrucao',                true,  now() - interval '4 days',  now() - interval '4 days'),
('King Air 350',           'Textron Aviation', 2011, 'Turboelice executivo',                           false, now() - interval '2 days',  now() - interval '2 days'),
('340',                    'Saab',             1989, 'Turboelice regional',                            true,  now(),                       now());
